# Change these first
owner: alxhu-dev # Your GitHub organization or username, where this repository lives
repo: status.greifswald.lgbt # The name of this repository

sites:
  - name: Mastodon (IPv4)
    url: https://greifswald.lgbt
    ipv6: false
  - name: Mastodon (IPv6)
    url: https://greifswald.lgbt
    ipv6: true
  - name: Pride Greifswald (Website, IPv4)
    url: https://pride-greifswald.de
    ipv6: false
  - name: Pride Greifswald (Website, IPv6)
    url: https://pride-greifswald.de
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.greifswald.lgbt
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Statuspage für Pride Greifswald
  introTitle: ""
  introMessage: Auf dieser Seite sind die Status der Online-Services von Pride Greifswald einsehbar.
  navbar:
    - title: Status
      href: /
    - title: Mastodon
      href: https://greifswald.lgbt
    - title: Pride Greifswald
      href: https://pride-greifswald.de
    - title: Impressum
      href: https://pride-greifswald.de/impressum/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
